controller_list:
  - name: fake_edo_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_edo_eef_controller
    joints:
      []
initial:  # Define initial robot poses.
  - group: edo_arm
    pose: home